apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: padel-app
  app.kubernetes.io/component: backend

images:
- name: victor2campos/ci-backend
  newName: victor2campos/ci-backend
  newTag: latest
