apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app

resources:
- ../../base/database
- ../../base/backend
- ../../base/frontend
- ingress.yaml

labels:
- pairs:
    environment: production
    managed-by: argocd
