apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app-prod

resources:
- ../../base/database
- ../../base/backend
- ../../base/frontend
- ingressroute.yaml

labels:
- pairs:
    environment: production
    managed-by: argocd

images:
- name: victor2campos/ci-backend
  newTag: latest
- name: victor2campos/ci-frontend
  newTag: latest