apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: padel-app
  app.kubernetes.io/component: database
