apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/name: padel-app
    app.kubernetes.io/component: frontend

images:
- name: victor2campos/ci-frontend
  newName: victor2campos/ci-frontend
  newTag: latest
