apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app-dev

resources:
- ../../base/database
- ../../base/backend
- ../../base/frontend
- ingressroute.yaml

namePrefix: dev-

labels:
- pairs:
    environment: develop
    managed-by: argocd

namePrefix: dev-

replicas:
- name: backend
  count: 1
- name: frontend
  count: 1

images:
- name: victor2campos/ci-backend
  newTag: latest
- name: victor2campos/ci-frontend
  newTag: latest