apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: padel-app-dev

resources:
- ../../base/database
- ../../base/backend
- ../../base/frontend
- ingress.yaml

labels:
- pairs:
    environment: develop
    managed-by: argocd

namePrefix: dev-

replicas:
- name: backend
  count: 1
- name: frontend
  count: 1
