apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-tests
  namespace: tfm-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-tests
  template:
    metadata:
      labels:
        app: backend-tests
    spec:
      containers:
      - name: backend
        image: victor2campos/unittest-infra
        env:
        - name: DB_HOST
          value: db-test
        - name: DB_PASSWORD
          value: test_password
        - name: DB_USER
          value: test_user
        - name: DB_NAME
          value: padel_db_test
        command: ["pytest"]
        args:
        - test/tests/integration
        - -v
        - --cov=./backend
        - --cov-report=html:/app/test/tests/integration/htmlcov
        - --tb=short
